services:
  - type: web
    name: roster-ga
    runtime: python
    pythonVersion: "3.11.9"
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        sync: false